name: code-quality-check 

on:
  workflow_call:
    
  # push:
  #   branches: [developmemt]
  #   paths-ignore:
  #     
  # workflow_dispatch:
    
jobs:
  backend-code-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - name: Checkout source code 
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.3'
        cache: true
        cache-dependency-path: go.sum

    - name: Check formatting 
      run: | 
        unformatted=$(gofmt -l .) 
        if [ -n "$unformatted" ]; 
        then echo "The following files are not formatted:" 
        echo "$unformatted" exit 1 
        fi
    
    - name: Run golangci-lint 
      uses: golangci/golangci-lint-action@v8 
      with: 
        working-directory: backend
        version: latest
        latest args: --timeout=5m 

  frontend-code-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-map: '22'

    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Run Linter
      run: htmlhint "**/*.html"

    - name: Lint CSS
      working-directory: ./frontend
      run: |
        echo '{"rules": {"color-no-invalid-hex": true, "block-no-empty": true}}' > .stylelintrc.json
        npx stylelint "**/*.css" --config .stylelintrc.json
        

    - name: Lint JS
      working-directory: ./frontend
      run: |
        echo 'export default [{ languageOptions: { globals: { window: "readonly", document: "readonly", localStorage: "readonly", fetch: "readonly", confirm: "readonly", setTimeout: "readonly", console: "readonly" } }, rules: { "no-undef": "error" } }];' > eslint.config.js
        npx eslint "**/*.js" --no-config-lookup --config eslint.config.js
        

  